default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: 'db'
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  port: 5432

development:
  <<: *default
  database: app_search_dev

test:
  <<: *default
  database: app_search_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  # DATABASE_URL="postgres://myuser:mypass@localhost/somedatabase"
