version: '3.2'

services: 
  db:
    image: postgres:12
    restart: always
    volumes: 
      - ./dbdata:/var/lib/postgresql/data
    hostname: raremark-db  
    environment: 
      - POSTGRES_USER=raremark
      - POSTGRES_PASSWORD=raremark
      - POSTGRES_DB=raremark_dev
      - PGDATA=/var/lib/postgresql/data
    networks: 
      - raremark
  
  admin:
    restart: always
    build: 
      context: .
      dockerfile: ./dockerfiles/Dockerfile-admin
    image: raremark_admin:dev
    hostname: reremark-admin
    container_name: raremark_admin
    environment: 
      - RAILS_ENV=development
      - RACK_ENV=development
      - POSTGRES_USER=raremark
      - POSTGRES_PASSWORD=raremark
    volumes: 
      - ./admin:/home/admin/adminapp
    ports: 
      - 3000:3000
    links: 
      - db
    tty: true
    networks: 
      - raremark
  
  search:
    restart: always
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile-search
    image: raremark_search:dev
    hostname: reremark-search
    container_name: raremark_search
    environment:
      - RAILS_ENV=development
      - RACK_ENV=development
      - POSTGRES_USER=raremark
      - POSTGRES_PASSWORD=raremark
    volumes:
      - ./search:/home/admin/searchapp
    ports:
      - 3001:3001
    links:
      - db
    tty: true
    networks:
      - raremark

networks:
  raremark:
    driver: "bridge"
volumes:
  dbdata:
    driver: "local"
