version: '3.2'

services:
  elasticsearch:
    image: elasticsearch:7.4.2
    environment:
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
    user: 1000:1001
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    networks:
      - raremark
    ports:
      - 9200:9200
      - 9300:9300

  db:
    image: postgres:12
    restart: always
    volumes: 
      - ./dbdata:/var/lib/postgresql/data
    hostname: raremark-db  
    environment: 
      - POSTGRES_USER=raremark
      - POSTGRES_PASSWORD=raremark
      - POSTGRES_DB=raremark_dev
      - PGDATA=/var/lib/postgresql/data
    networks: 
      - raremark
  
  admin:
    restart: always
    build: 
      context: .
      dockerfile: ./dockerfiles/Dockerfile-admin
    image: raremark_admin:dev
    hostname: reremark-admin
    container_name: raremark_admin
    environment: 
      - NODE_ENV=development
      - RAILS_ENV=development
      - RACK_ENV=development
      - POSTGRES_USER=raremark
      - POSTGRES_PASSWORD=raremark
      - ELASTICSEARCH_URL=elasticsearch
    ports:
      - 3000:3000
    links: 
      - db
      - elasticsearch
    tty: true
    networks: 
      - raremark
  
  search:
    restart: always
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile-search
    image: raremark_search:dev
    hostname: reremark-search
    container_name: raremark_search
    environment:
      - NODE_ENV=development
      - RAILS_ENV=development
      - RACK_ENV=development
      - POSTGRES_USER=raremark
      - POSTGRES_PASSWORD=raremark
      - ELASTICSEARCH_URL=elasticsearch
    ports:
      - 3001:3001
    links: 
      - db
      - elasticsearch
    tty: true
    networks: 
      - raremark

networks:
  raremark:
    driver: "bridge"
volumes:
  dbdata:
    driver: "local"
  esdata:
    driver: "local"
