FROM ruby:2.7.0

RUN apt-get update -qq && apt-get install -y \
    sudo nano build-essential apt-transport-https apt-utils libxml2-dev libxslt1-dev && \
    echo "34.228.211.243  registry-1.docker.io" >> /etc/hosts

# for a JS runtime
RUN curl -sL https://deb.nodesource.com/setup_12.x | bash -
RUN apt-get install -y nodejs gcc g++ make

# for yarn
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list && \
    apt-get update -qq && apt-get install -y yarn && \
    apt-get clean && yarn cache clean &&  \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Copy application code
COPY ./search /searchapp
WORKDIR /searchapp
RUN bundle install && bundle update --conservative && npm install && yarn install
RUN mkdir -p tmp/pids

# Expose the port to run the server
EXPOSE 3001

# change the access mode of entrypoint.sh
RUN ["chmod", "+x", "entrypoint.sh"]

# Set the entrypoint where the service start
ENTRYPOINT ./entrypoint.sh